export const path = {
    PUBLIC: "/",
    HOME: "",
    LOGIN: "login",
    PRODUCT: "product",
    BLOG: "blogs",
    BLOGDE: "blogs/:title",
    CART: "cart",
    OUR_SERVICE: "our-service",
    FAQ: "faqs",
    COLECTIONS: ":category",
    DETAIL_COLLECTION: "collections",
    DETAIL_PRODUCT: ":category/:pid/:title",
    FINAL_REGISTER: "finalregister/:status",
    RESET_PASSWORD: "reset-password/:token",
    DETAIL_BLOG: ":bid/:title",
    CONTACT: "contact-us",
    ADMIN: "admin",
    CREATE_PRODUCT: "create-product",
    DASHBOARD: "dashboard",
    MANAGER_ORDER: "manager-order",
    MANAGER_USER: "manager-user",
    MANAGER_BLOG: "manager-blog",
    CREATE_BLOG: "create-blog",

    MANAGER_PRODUCT: "manager-product",
    MENBER_LAYOUT: "menber",
    PERSONAL: "personal",
    EDIT_USER: "edit-user",
    CHECKOUT: "checkout",
};
